"""
Populates the database with categories, a demo admin user, and sample
projects covering every submenu item so no page on the site looks empty.

Run from the backend/ folder (needs the app package on the path):
    cd backend && python ../database/seed_data.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

from app.database import Base, SessionLocal, engine
from app.models.category import Category
from app.models.contact import ContactMessage  # noqa: F401 (ensures table is created)
from app.models.project import Project
from app.models.user import User
from app.auth.security import hash_password

ADMIN_EMAIL = "admin@portfolio.dev"
ADMIN_PASSWORD = "Admin@123"

CATEGORIES = [
    {"name": "Machine Learning", "slug": "machine-learning", "icon": "BrainCircuit",
     "description": "Classical ML algorithms applied to real business problems."},
    {"name": "Deep Learning", "slug": "deep-learning", "icon": "Network",
     "description": "Neural network architectures for vision, language, and sequence data."},
    {"name": "AI Agent", "slug": "ai-agent", "icon": "Bot",
     "description": "LLM-powered autonomous and semi-autonomous agents."},
    {"name": "Automation", "slug": "automation", "icon": "Workflow",
     "description": "Industry automation that removes manual, repetitive work."},
]

def p(title, slug, category_slug, method, short, problem, dataset, business, steps,
      tools, tech, metrics, results, learning, difficulty="Intermediate", status="Completed"):
    return dict(
        title=title, slug=slug, category_slug=category_slug, method_or_algorithm=method,
        short_description=short, problem_statement=problem, dataset_description=dataset,
        business_use_case=business, workflow_steps=steps, tools_used=tools,
        technologies_used=tech, evaluation_metrics=metrics, results=results,
        key_learning=learning, difficulty_level=difficulty, status=status,
        github_url="https://github.com/your-username/" + slug,
        demo_url="", dataset_url="", image_url="",
    )

PROJECTS = [
    # ---------------- MACHINE LEARNING ----------------
    p("House Price Prediction", "house-price-prediction", "machine-learning", "Linear Regression",
      "Predicts house sale price from property features.",
      "Estimate fair market value of a house before listing.",
      "Ames/Boston-style housing dataset with size, location, and condition features.",
      "Helps agents and sellers price listings competitively instead of guessing.",
      "Collect data -> Clean & impute -> EDA on price drivers -> Feature engineering (age, price/sqft) -> Train Linear Regression baseline -> Regularize with Ridge/Lasso -> Evaluate -> Deploy",
      "Python, Pandas, Scikit-learn, Matplotlib", "Linear Regression, Ridge, Lasso",
      "RMSE, MAE, R2", "R2 = 0.87, RMSE reduced 18% vs. mean-price baseline.",
      "Regularization mattered more than adding features once multicollinearity appeared.",
      "Beginner"),
    p("Heart Disease Prediction", "heart-disease-prediction", "machine-learning", "Logistic Regression",
      "Classifies patients as at-risk of heart disease from clinical measurements.",
      "Early risk flagging from routine checkup data.",
      "UCI Heart Disease dataset (age, cholesterol, blood pressure, etc.).",
      "Supports doctors in prioritizing follow-up tests for high-risk patients.",
      "EDA on risk factors -> Handle missing/categorical data -> Train Logistic Regression -> Tune decision threshold -> Evaluate with recall focus -> Explain coefficients",
      "Python, Scikit-learn, Seaborn", "Logistic Regression",
      "Recall, ROC-AUC, Precision", "Recall = 0.90 on at-risk class, ROC-AUC = 0.91.",
      "Chose recall over accuracy since a missed at-risk patient is the costly error.",
      "Beginner"),
    p("Loan Approval Prediction", "loan-approval-prediction", "machine-learning", "Decision Tree",
      "Predicts whether a loan application should be approved.",
      "Speed up loan triage while keeping decisions explainable.",
      "Bank loan applicant dataset with income, credit history, and loan amount.",
      "Gives underwriters an explainable first-pass decision, not a black box.",
      "Clean applicant data -> Encode categoricals -> Train Decision Tree -> Prune with max_depth/min_samples -> Visualize tree -> Evaluate",
      "Python, Scikit-learn, Graphviz", "Decision Tree Classifier",
      "Accuracy, F1, Confusion Matrix", "F1 = 0.84; tree depth limited to 5 for explainability.",
      "A shallower, explainable tree was preferred by the (simulated) business stakeholder over a marginally more accurate deep tree.",
      "Beginner"),
    p("Customer Churn Prediction", "customer-churn-prediction", "machine-learning", "Random Forest",
      "Predicts which telecom customers are likely to cancel their subscription.",
      "Retention teams have limited outreach capacity and need a ranked risk list.",
      "IBM Telco Customer Churn dataset (~7,000 customers).",
      "Lets retention teams target the highest-risk customers first.",
      "EDA on churn drivers -> Encode & scale -> Baseline Logistic Regression -> Random Forest -> Hyperparameter tuning -> Feature importance -> Deploy as API",
      "Python, Scikit-learn, XGBoost, FastAPI", "Random Forest, XGBoost",
      "Recall, F1, ROC-AUC", "Recall on churners improved from 55% (baseline) to 81% (tuned RF).",
      "Contract type was the single strongest churn driver — a real lever for the business, not just a modeling detail.",
      "Intermediate"),
    p("Customer Segmentation", "customer-segmentation-kmeans", "machine-learning", "K-Means Clustering",
      "Groups customers into behavioral segments from purchase data.",
      "Enables targeted marketing instead of one-size-fits-all campaigns.",
      "E-commerce transaction dataset (RFM: recency, frequency, monetary).",
      "Marketing can tailor offers per segment (e.g., high-value vs. at-risk customers).",
      "Compute RFM features -> Scale -> Elbow method + silhouette score to pick k -> Fit K-Means -> Profile each cluster -> Visualize with PCA",
      "Python, Scikit-learn, Plotly", "K-Means, PCA (for visualization)",
      "Silhouette Score, Inertia", "Silhouette score 0.61 with k=4; identified a clear 'high-value loyal' segment worth 40% of revenue.",
      "Unsupervised results are only useful once translated into a business narrative per cluster.",
      "Beginner"),
    p("Credit Card Fraud Detection", "credit-card-fraud-detection", "machine-learning", "Gradient Boosting / XGBoost",
      "Flags fraudulent transactions in a highly imbalanced dataset.",
      "Every missed fraud is stolen money; every false alarm blocks a real customer.",
      "Kaggle/ULB Credit Card Fraud dataset, 284,807 transactions, 0.17% fraud.",
      "Deployed as a real-time scoring API mimicking a payments pipeline.",
      "EDA on class imbalance -> Class weighting vs. SMOTE comparison -> Train XGBoost -> Tune threshold on cost matrix -> Deploy via FastAPI + Docker",
      "Python, XGBoost, FastAPI, Docker", "XGBoost, SMOTE",
      "Precision-Recall AUC (not ROC-AUC)", "PR-AUC = 0.86; threshold tuned to the business cost tradeoff, not the default 0.5.",
      "At extreme imbalance, ROC-AUC is misleadingly high — PR-AUC is the honest scoreboard.",
      "Advanced"),
    p("Email Spam Classification", "email-spam-classification-svm", "machine-learning", "Support Vector Machine",
      "Classifies emails as spam or legitimate.",
      "Reduce inbox clutter and phishing exposure.",
      "SMS Spam Collection / Enron spam dataset.",
      "Filters spam automatically before it reaches an inbox.",
      "Text cleaning -> TF-IDF vectorization -> Train linear SVM -> Tune C and kernel -> Evaluate",
      "Python, Scikit-learn, NLTK", "Support Vector Machine (linear kernel)",
      "Precision, Recall, F1", "F1 = 0.97 on the spam class with a linear kernel.",
      "A simple linear SVM on TF-IDF outperformed a more complex RBF kernel here — proved with a direct comparison, not assumed.",
      "Intermediate"),
    p("Movie Recommendation (Similarity Search)", "movie-recommendation-knn", "machine-learning", "K-Nearest Neighbors",
      "Recommends similar movies based on user rating patterns.",
      "Improves content discovery and watch-time on a streaming-style platform.",
      "MovieLens 100k dataset.",
      "Drives engagement through 'more like this' recommendations.",
      "Build user-item matrix -> Normalize ratings -> Fit KNN with cosine similarity -> Generate top-N recommendations -> Evaluate offline",
      "Python, Scikit-learn, Surprise", "K-Nearest Neighbors (item-based)",
      "Precision@K, RMSE", "Precision@10 = 0.78 on held-out ratings.",
      "Item-based KNN was more stable than user-based KNN as the user base grew (fewer cold-start issues).",
      "Beginner"),
    p("Spam/Disease Diagnosis with Naive Bayes", "text-classification-naive-bayes", "machine-learning", "Naive Bayes",
      "Fast baseline text classifier for short medical symptom descriptions.",
      "Quick triage of patient-reported symptoms into likely categories.",
      "Symptom-to-diagnosis text dataset.",
      "Gives a fast, cheap baseline before investing in a heavier deep learning model.",
      "Clean text -> Bag-of-words -> Train Multinomial Naive Bayes -> Compare against TF-IDF+SVM baseline -> Evaluate",
      "Python, Scikit-learn", "Multinomial Naive Bayes",
      "Accuracy, F1 (macro)", "F1 = 0.79, trained in under a second — used as the fast baseline for comparison.",
      "Naive Bayes is a criminally underrated first baseline: near-zero training cost buys you a real comparison anchor.",
      "Beginner"),
    p("Dimensionality Reduction for Gene Expression Data", "gene-expression-pca", "machine-learning", "Principal Component Analysis",
      "Reduces thousands of gene-expression features to a handful of components for visualization and downstream modeling.",
      "High-dimensional biological data is unusable directly for visualization or many classifiers.",
      "Public gene expression cancer-subtype dataset.",
      "Lets researchers visualize sample clusters and feed a lower-dimensional input into a classifier.",
      "Standardize features -> Fit PCA -> Choose components via explained variance -> Visualize in 2D/3D -> Feed into downstream classifier",
      "Python, Scikit-learn, Plotly", "Principal Component Analysis",
      "Explained Variance Ratio, Downstream Accuracy", "First 10 components explained 92% of variance; downstream classifier accuracy held within 2% of the full-feature model.",
      "PCA traded a small accuracy cost for a 50x reduction in feature count and much faster training.",
      "Intermediate"),

    # ---------------- DEEP LEARNING ----------------
    p("Handwritten Digit Recognition", "handwritten-digit-recognition-ann", "deep-learning", "Artificial Neural Network",
      "Classifies handwritten digits (0-9) from pixel data.",
      "The canonical entry point into neural networks, done rigorously with a full comparison.",
      "MNIST (70,000 handwritten digit images).",
      "Illustrates core deep learning workflow before scaling to more complex vision tasks.",
      "Normalize pixel data -> Build a 2-hidden-layer ANN -> Train with Adam -> Compare against a Logistic Regression baseline -> Evaluate",
      "Python, PyTorch", "Feedforward ANN",
      "Accuracy, Confusion Matrix", "Test accuracy 98.1%, +6 points over the logistic regression baseline.",
      "Even a shallow ANN massively outperforms linear models the moment inputs are pixels, not tabular features.",
      "Beginner"),
    p("Image Classification", "image-classification-cnn", "deep-learning", "Convolutional Neural Network",
      "Classifies images into categories using convolutional layers.",
      "Automates visual categorization tasks (e.g., product images, defect vs. no-defect).",
      "CIFAR-10 (60,000 32x32 color images, 10 classes).",
      "Shows the jump from ANN to CNN and quantifies exactly what convolution buys you.",
      "Data augmentation -> Build CNN (conv/pool/dropout blocks) -> Train -> Compare vs. plain ANN baseline -> Evaluate -> Grad-CAM for interpretability",
      "Python, TensorFlow/Keras", "CNN",
      "Accuracy, Top-3 Accuracy", "Test accuracy 84% vs. 52% for a plain ANN on the same data.",
      "Convolution's parameter sharing is what makes vision tasks tractable — proven here with a direct ANN-vs-CNN comparison.",
      "Intermediate"),
    p("Sentiment Analysis on Reviews", "sentiment-analysis-rnn-lstm", "deep-learning", "Recurrent Neural Network",
      "Classifies product review sentiment using a sequence model.",
      "Monitor brand sentiment at scale instead of manually reading reviews.",
      "IMDB 50k movie reviews.",
      "Automates sentiment monitoring for support/marketing teams.",
      "Tokenize + pad sequences -> Embedding layer -> Simple RNN baseline -> Compare against LSTM -> Evaluate",
      "Python, TensorFlow/Keras", "RNN",
      "F1 (macro), Accuracy", "F1 = 0.85 — used as the baseline the LSTM/GRU project below improves on.",
      "Plain RNNs struggle with long reviews due to vanishing gradients — motivates the LSTM version directly.",
      "Intermediate"),
    p("Sentiment Analysis with LSTM/GRU", "sentiment-analysis-lstm-gru", "deep-learning", "LSTM / GRU",
      "Improves review sentiment classification using gated recurrent architectures.",
      "Same business goal as the RNN project — quantifies the improvement gated units provide.",
      "IMDB 50k movie reviews (same dataset as the RNN baseline for a fair comparison).",
      "More reliable sentiment signal for longer-form reviews.",
      "Reuse RNN preprocessing pipeline -> Swap in LSTM and GRU layers -> Tune sequence length and dropout -> Compare all three architectures side by side",
      "Python, TensorFlow/Keras", "LSTM, GRU",
      "F1 (macro), Accuracy", "LSTM F1 = 0.90 vs. plain RNN's 0.85 on identical data/splits.",
      "Gated units earn their complexity specifically on longer sequences — the gap over plain RNN grows with review length.",
      "Intermediate"),
    p("Text Classification with Transformers", "text-classification-transformers", "deep-learning", "Transformers",
      "Fine-tunes a pretrained transformer for multi-class text classification.",
      "State-of-the-art accuracy for a text categorization business need (e.g., support ticket topics).",
      "AG News / custom labeled ticket text.",
      "Highest-accuracy option when latency budget allows a transformer in production.",
      "Tokenize with a pretrained tokenizer -> Fine-tune DistilBERT -> Compare against the LSTM/GRU project -> Evaluate -> Export for serving",
      "Python, HuggingFace Transformers, PyTorch", "DistilBERT (fine-tuned)",
      "F1 (macro), Latency (p95)", "F1 = 0.94, a 4-point gain over LSTM/GRU at roughly 3x the inference latency.",
      "Transformers win on accuracy but the latency cost is real — worth stating the tradeoff instead of defaulting to 'BERT is always better.'",
      "Advanced"),
    p("Anomaly Detection with Autoencoders", "anomaly-detection-autoencoders", "deep-learning", "Autoencoders",
      "Detects unusual patterns (e.g., manufacturing defects, unusual transactions) via reconstruction error.",
      "Labeled anomaly data is scarce — autoencoders learn 'normal' and flag what doesn't fit.",
      "Sensor/transaction data with rare, unlabeled anomalies.",
      "Flags anomalies without needing large labeled anomaly datasets.",
      "Train autoencoder only on normal data -> Compute reconstruction error on holdout -> Set threshold from error distribution -> Evaluate against known anomalies",
      "Python, PyTorch", "Autoencoder",
      "Precision/Recall on flagged anomalies, Reconstruction Error", "Recall = 0.88 on injected anomalies at a threshold tuned for <5% false-positive rate.",
      "Unsupervised anomaly detection needs a business-defined threshold, not a fixed default — the FP/FN tradeoff has to be a stakeholder decision.",
      "Advanced"),
    p("Medical Image Classification via Transfer Learning", "pneumonia-detection-transfer-learning", "deep-learning", "Transfer Learning",
      "Classifies chest X-rays as pneumonia vs. normal using a pretrained backbone.",
      "Assistive triage tool to help radiology prioritize likely-positive scans (not a diagnostic replacement).",
      "Chest X-Ray Images (Pneumonia) dataset, ~5,800 images.",
      "Speeds up radiology triage in a resource-constrained setting.",
      "Train a CNN from scratch as baseline -> Fine-tune ResNet50/EfficientNet -> Data augmentation -> Threshold tuned for recall -> Add Grad-CAM for interpretability",
      "Python, TensorFlow/Keras, Grad-CAM", "ResNet50 / EfficientNet (transfer learning)",
      "Recall (Sensitivity), AUC", "Recall improved from 84% (from-scratch CNN) to 95% (transfer learning).",
      "Transfer learning's real advantage shows up precisely when labeled data is limited, as in most medical imaging problems.",
      "Advanced"),

    # ---------------- AI AGENT ----------------
    p("Personal AI Assistant", "personal-ai-assistant", "ai-agent", "Personal AI Assistant",
      "A conversational agent that manages reminders, answers questions, and drafts messages.",
      "Reduce time spent on routine personal admin tasks.",
      "N/A — built on live conversation + tool APIs (calendar, notes).",
      "Demonstrates tool-calling and multi-turn memory in an LLM agent.",
      "Define tool schema (calendar, notes, search) -> System prompt + persona design -> LLM function-calling loop -> Add short-term memory -> Test multi-turn tasks",
      "Python, LangChain/LLM SDK, function calling", "GPT/Claude-class LLM + tool calling",
      "Task success rate (manual eval)", "18/20 realistic multi-step tasks completed correctly in manual testing.",
      "Most failures were tool-argument formatting, not reasoning — solved with stricter schema validation before the call.",
      "Intermediate"),
    p("AI Research Assistant", "ai-research-assistant", "ai-agent", "Research Agent",
      "Given a topic, searches, reads, and synthesizes multiple sources into a structured summary.",
      "Cuts hours of manual literature/web research down to minutes.",
      "Web search results + scraped articles per query.",
      "Analysts get a sourced first-draft summary instead of starting from a blank page.",
      "Query decomposition -> Web search tool calls -> Scrape + chunk content -> Summarize per source -> Synthesize final report with citations",
      "Python, LangChain, vector store, search API", "LLM + retrieval + tool use",
      "Citation accuracy, summary relevance (manual eval)", "92% of citations verified as correctly attributed to source content.",
      "Forcing the agent to cite verbatim snippets (not paraphrase) before synthesizing cut hallucinated claims sharply.",
      "Advanced"),
    p("Resume Screening AI Agent", "resume-screening-ai-agent", "ai-agent", "Resume Screening Agent",
      "Screens resumes against a job description and ranks candidates with reasoning.",
      "Speeds up first-pass recruiting triage for high-volume roles.",
      "Sample resumes + job description dataset (synthetic/anonymized).",
      "Recruiters get a ranked shortlist with an explanation, not just a score.",
      "Parse resume text -> Extract structured fields (skills, experience) -> Embed JD + resume -> LLM scoring with rationale -> Rank candidates",
      "Python, HuggingFace embeddings, LLM prompting", "LLM + embeddings (RAG-lite)",
      "Ranking agreement with human reviewer", "81% top-5 overlap with a human recruiter's shortlist on a held-out test set.",
      "The rationale text mattered more to end users than the score itself — recruiters wanted to see *why*, not just a number.",
      "Advanced"),
    p("Document Q&A Agent (RAG)", "document-qa-rag-agent", "ai-agent", "Document Q&A Agent",
      "Answers questions grounded in a set of uploaded documents.",
      "Lets non-technical users query internal documents (policies, manuals) in plain English.",
      "Company policy PDFs / manuals (sample set).",
      "Reduces time employees spend searching internal documentation.",
      "Chunk documents -> Embed + store in vector DB -> Retrieve top-k chunks per query -> LLM answers with citations -> Guard against hallucination with 'answer only from context' prompting",
      "Python, LangChain, FAISS/Chroma, LLM", "Retrieval-Augmented Generation (RAG)",
      "Answer accuracy, citation correctness", "89% of answers verified correct and grounded in the cited chunk.",
      "Chunk size/overlap tuning mattered more to answer quality than the choice of LLM.",
      "Advanced"),
    p("RAG-based Agent over a Codebase", "rag-based-agent-codebase", "ai-agent", "RAG-based Agent",
      "Answers questions about a codebase by retrieving relevant files/functions before answering.",
      "Helps new developers or recruiters understand a codebase without reading it all.",
      "This portfolio's own backend/frontend code as the retrieval corpus.",
      "Demonstrates RAG applied to code, not just prose documents.",
      "Chunk code by function/file -> Embed with a code-aware embedding model -> Retrieve relevant chunks -> LLM answers with file/line references",
      "Python, LangChain, code-aware embeddings", "RAG over source code",
      "Answer correctness (manual eval)", "Correctly located the relevant file/function in 9/10 test questions about this repo.",
      "Chunking by function boundary (not fixed character length) noticeably improved retrieval precision for code.",
      "Advanced"),
    p("Data Analysis Agent", "data-analysis-agent", "ai-agent", "Data Analysis Agent",
      "Takes a natural-language question about a dataset and returns an answer plus a chart.",
      "Lets non-technical stakeholders query data without writing SQL/pandas themselves.",
      "Sample sales/business CSV dataset.",
      "Cuts the ad-hoc analytics request queue for a data team.",
      "Parse question -> Generate pandas/SQL code via LLM -> Execute safely in a sandboxed runner -> Auto-generate a chart -> Return answer + chart",
      "Python, Pandas, LLM code generation", "LLM + code generation + execution sandbox",
      "Correct-answer rate (manual eval)", "85% of natural-language queries produced a correct answer and chart on the first try.",
      "Sandboxing generated code (no arbitrary exec) was the non-negotiable engineering piece, not an afterthought.",
      "Advanced"),
    p("Customer Support Agent", "customer-support-agent", "ai-agent", "Customer Support Agent",
      "Answers common customer questions and escalates complex ones to a human.",
      "Reduces first-response time and human workload on repetitive tickets.",
      "Sample support ticket + FAQ dataset.",
      "Handles the long tail of repetitive tickets so agents focus on complex cases.",
      "Intent classification -> RAG over FAQ/knowledge base -> Confidence-based escalation to human -> Log all conversations for review",
      "Python, LangChain, LLM, vector store", "RAG + intent classification",
      "Deflection rate, escalation accuracy", "62% of tickets fully resolved by the agent without human escalation.",
      "A conservative escalation threshold (when in doubt, hand off to a human) built more user trust than maximizing deflection rate.",
      "Intermediate"),
    p("Multi-Agent Research & Report Workflow", "multi-agent-workflow", "ai-agent", "Multi-Agent Workflow",
      "Coordinates multiple specialized agents (researcher, writer, reviewer) to produce a final report.",
      "Complex tasks benefit from role specialization the way a human team would divide work.",
      "N/A — orchestration project over LLM agents and tool calls.",
      "Shows agent orchestration beyond a single-agent chatbot.",
      "Define agent roles and handoff protocol -> Researcher agent gathers info -> Writer agent drafts -> Reviewer agent critiques and requests revisions -> Final output",
      "Python, LangGraph/CrewAI-style orchestration, LLM", "Multi-agent orchestration",
      "Task completion quality (manual eval)", "Reviewer-agent loop caught factual/formatting issues in 70% of first drafts before human review.",
      "A dedicated reviewer agent with a narrow checklist caught more issues than asking one agent to 'double check itself.'",
      "Advanced"),

    # ---------------- AUTOMATION ----------------
    p("Automated Power BI Report Refresh Notification", "powerbi-report-refresh-automation", "automation", "Excel / Power BI Automation",
      "Automatically checks Power BI dataset refresh status and notifies stakeholders on failure.",
      "Manual process: someone had to open Power BI daily to check if the refresh succeeded.",
      "Manually checked refresh status daily, delayed failure discovery by up to 24 hours.",
      "Python script polls Power BI REST API for refresh status and posts to Slack/Teams/email on failure.",
      "Call Power BI REST API -> Parse refresh status -> On failure, send alert (email/Slack) -> Schedule via cron/Task Scheduler -> Log history",
      "Python, Power BI REST API, Slack/Teams webhook", "REST API polling, scheduled automation",
      "Time saved, detection latency", "Failure detection time dropped from ~24 hours to under 15 minutes.",
      "Reliable alerting infrastructure mattered more than the automation script itself — silent failures are worse than the manual process.",
      "Beginner"),
    p("Excel Data Cleaning Automation", "excel-data-cleaning-automation", "automation", "Excel / Power BI Automation",
      "Automates cleaning of messy, recurring Excel exports (formatting, duplicates, missing values).",
      "Analysts spent hours each week manually cleaning the same recurring report format.",
      "Manual cleanup in Excel, ~3 hours/week, error-prone and inconsistent between analysts.",
      "Script standardizes column names, removes duplicates, fixes types, and outputs a clean file automatically.",
      "Define cleaning rules from historical manual edits -> Build a reusable Python cleaning pipeline (openpyxl/pandas) -> Validate against manual output -> Schedule to run on file arrival",
      "Python, Pandas, openpyxl", "Rule-based data cleaning pipeline",
      "Time saved, error rate", "Cut weekly cleaning time from ~3 hours to under 5 minutes; eliminated inconsistent manual edits.",
      "Codifying the analyst's implicit cleaning rules was the real work — the script itself was straightforward once rules were explicit.",
      "Beginner"),
    p("Email Classification Automation", "email-classification-automation", "automation", "Email Automation",
      "Automatically classifies and routes incoming emails to the right team/folder.",
      "Support inbox required manual triage before routing to the right team.",
      "Manually read and forwarded each email, ~2 minutes per email.",
      "NLP classifier reads incoming email subject/body and auto-routes/labels it.",
      "Collect labeled historical emails -> Train text classifier (TF-IDF + Logistic Regression) -> Integrate with email API (IMAP/Gmail API) -> Auto-label/route on arrival",
      "Python, Scikit-learn, Gmail API", "Text classification + email API integration",
      "Time saved, routing accuracy", "Routing accuracy 91%; manual triage time reduced by ~80%.",
      "A simple classical ML model was sufficient here — the automation/integration plumbing was the harder half of the project, not the model.",
      "Intermediate"),
    p("Invoice Data Extraction Automation", "invoice-data-extraction-automation", "automation", "Document Processing Automation",
      "Extracts structured fields (vendor, amount, date) from PDF/scanned invoices automatically.",
      "Finance team manually retyped invoice data into the accounting system.",
      "Manual data entry from PDF invoices, ~5 minutes per invoice, occasional typos.",
      "OCR + information extraction pipeline reads invoices and populates structured records automatically.",
      "OCR text extraction (Tesseract) -> Layout-aware field extraction -> Validate against known formats -> Push structured data to accounting system API",
      "Python, Tesseract OCR, regex/LLM-assisted extraction", "OCR + structured information extraction",
      "Time saved, extraction accuracy", "Field extraction accuracy 94%; processing time per invoice cut from 5 minutes to ~10 seconds.",
      "Layout-aware extraction (not just raw OCR text) was necessary once invoice formats varied across vendors.",
      "Intermediate"),
    p("Web Scraping for Market Data", "web-scraping-market-data-automation", "automation", "Web Scraping Automation",
      "Scrapes competitor pricing/market data on a schedule and compiles it into a report.",
      "Analysts manually checked competitor websites for pricing changes.",
      "Manual weekly price checks across multiple competitor sites.",
      "Scheduled scraper collects pricing data and flags changes automatically.",
      "Build site-specific scrapers (requests/BeautifulSoup, Selenium for JS-heavy pages) -> Store data with timestamps -> Diff against previous run -> Alert on significant changes -> Schedule via cron",
      "Python, BeautifulSoup, Selenium, Pandas", "Web scraping + scheduled diffing",
      "Time saved, data freshness", "Weekly manual task automated to a nightly run; price-change detection latency cut from days to hours.",
      "Handling site structure changes gracefully (retries + alerting on scrape failure) mattered as much as the scraping logic itself.",
      "Intermediate"),
    p("Data Pipeline Automation for Daily Reporting", "data-pipeline-automation-daily-reporting", "automation", "Data Pipeline Automation",
      "Automates the daily ETL process feeding a business reporting dashboard.",
      "Someone manually ran extraction/cleaning scripts each morning before reports were usable.",
      "Manual daily ETL run, prone to being skipped or run late.",
      "Orchestrated pipeline extracts, transforms, and loads data on a fixed schedule with failure alerts.",
      "Define ETL steps -> Orchestrate with Airflow/cron -> Add data quality checks -> Alert on failure -> Log run history",
      "Python, Airflow, Pandas, SQL", "ETL orchestration",
      "On-time delivery rate, failure detection", "On-time report delivery improved from ~70% to 99% of days.",
      "Automated data-quality checks caught two real upstream data issues before they reached the dashboard.",
      "Intermediate"),
    p("Workflow Automation for Approvals", "workflow-automation-approvals", "automation", "Workflow Automation",
      "Automates a multi-step approval workflow (request -> review -> approval -> notification).",
      "Manual email-chain approvals were slow and easy to lose track of.",
      "Manual email-based approval chain, average 3-day turnaround.",
      "Automated workflow tracks state, routes to the right approver, and notifies all parties on status change.",
      "Model workflow states -> Build routing logic -> Integrate notifications (email/Slack) -> Add audit log -> Deploy as a lightweight internal tool",
      "Python, FastAPI, Celery, email/Slack API", "Workflow/state-machine automation",
      "Turnaround time, audit completeness", "Average approval turnaround cut from 3 days to under 6 hours.",
      "A visible audit trail was the feature stakeholders valued most — more than the speed improvement itself.",
      "Intermediate"),
    p("HR Recruitment Screening Automation", "hr-recruitment-automation", "automation", "HR / Recruitment Automation",
      "Automates initial resume screening and interview scheduling for high-volume roles.",
      "Recruiters manually screened hundreds of resumes and coordinated scheduling by email.",
      "Manual resume review + back-and-forth scheduling emails, days of recruiter time per role.",
      "Automated pipeline pre-screens resumes and auto-schedules interviews for qualified candidates.",
      "Parse resumes -> Rule/ML-based pre-screening -> Auto-send scheduling link to qualified candidates -> Sync to calendar -> Notify recruiter of shortlist",
      "Python, calendar API, resume parsing", "Rule-based + ML pre-screening automation",
      "Time saved, screen-to-schedule time", "Recruiter screening time reduced ~65%; average time-to-schedule cut from 4 days to same-day.",
      "Automating scheduling (not just screening) is where most of the actual time savings came from.",
      "Intermediate"),
    p("Customer Support Ticket Automation", "customer-support-ticket-automation", "automation", "Customer Support Automation",
      "Automates ticket tagging, prioritization, and routing for a support inbox.",
      "Support ops manually tagged and prioritized every incoming ticket before routing.",
      "Manual triage of all incoming tickets, inconsistent prioritization between shifts.",
      "Automation tags, scores urgency, and routes each ticket the moment it arrives.",
      "Classify ticket category -> Score urgency from keywords/SLA rules -> Auto-route to the right queue -> Notify on high-urgency tickets -> Log for reporting",
      "Python, FastAPI, text classification", "Rule-based + ML ticket automation",
      "Time saved, routing consistency", "Manual triage time eliminated; urgent-ticket response time improved by 45%.",
      "This project became the seed for the full 'Support Ticket Auto-Router' capstone in the Automation + AI Agent overlap.",
      "Intermediate"),
]


def run():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        category_map = {}
        for cat in CATEGORIES:
            existing = db.query(Category).filter(Category.slug == cat["slug"]).first()
            if not existing:
                existing = Category(**cat)
                db.add(existing)
                db.commit()
                db.refresh(existing)
            category_map[cat["slug"]] = existing.id

        created = 0
        for proj in PROJECTS:
            if db.query(Project).filter(Project.slug == proj["slug"]).first():
                continue
            data = proj.copy()
            data["category_id"] = category_map[data.pop("category_slug")]
            db.add(Project(**data))
            created += 1
        db.commit()

        if not db.query(User).filter(User.email == ADMIN_EMAIL).first():
            db.add(User(
                name="Portfolio Admin",
                email=ADMIN_EMAIL,
                password_hash=hash_password(ADMIN_PASSWORD),
                role="admin",
            ))
            db.commit()

        print(f"Seeded {len(category_map)} categories and {created} new projects.")
        print(f"Demo admin login -> email: {ADMIN_EMAIL}  password: {ADMIN_PASSWORD}")
    finally:
        db.close()


if __name__ == "__main__":
    run()
